[RSDungeonsConfig]
addDungeonsToModdedBiomes = true

[RSDungeonsConfig.spawnrate]
badlandsDungeonSpawnrate = 8
darkForestDungeonSpawnrate = 8
desertDungeonSpawnrate = 8
jungleDungeonSpawnrate = 8
mushroomDungeonSpawnrate = 8
snowDungeonSpawnrate = 8
swampDungeonSpawnrate = 8
endDungeonSpawnrate = 8
netherDungeonSpawnrate = 8
oceanDungeonSpawnrate = 8

[RSDungeonsConfig.minHeight]
badlandsDungeonMinHeight = 2
darkForestDungeonMinHeight = 2
desertDungeonMinHeight = 2
jungleDungeonMinHeight = 2
mushroomDungeonMinHeight = 2
snowDungeonMinHeight = 2
swampDungeonMinHeight = 2
endDungeonMinHeight = 2
netherDungeonMinHeight = 2
oceanDungeonMinHeight = 3

[RSDungeonsConfig.maxHeight]
badlandsDungeonMaxHeight = 255
darkForestDungeonMaxHeight = 255
desertDungeonMaxHeight = 255
jungleDungeonMaxHeight = 255
mushroomDungeonMaxHeight = 255
snowDungeonMaxHeight = 255
swampDungeonMaxHeight = 255
endDungeonMaxHeight = 255
netherDungeonMaxHeight = 255
oceanDungeonMaxHeight = 255
[RSMainConfig.misc]
addMiscToModdedBiomes = true
boulderTiny = true
boulderGiant = false
hornedSwampTree = true
[RSMainConfig.jungleFortress]
jungleFortressSpawnrate = 32
silverfishSpawnrateJF = 0.5
lootChestsJF = true
addJungleFortressToModdedBiomes = true
[RSMainConfig.shipwrecks]
endShipwreckSpawnrate = 23
addEndShipwreckToModdedBiomes = false
[RSMainConfig.igloos]
grassyIglooSpawnrate = 20
addGrassyIglooToModdedBiomes = true
stoneIglooSpawnrate = 20
addStoneIglooToModdedBiomes = true
[RSTemplesConfig.temples]
netherWastelandTempleSpawnrate = 26
addNetherWastelandTempleToModdedBiomes = true
netherBasaltTempleSpawnrate = 26
addNetherBasaltTempleToModdedBiomes = true
netherCrimsonTempleSpawnrate = 26
addNetherCrimsonTempleToModdedBiomes = true
netherWarpedTempleSpawnrate = 26
addNetherWarpedTempleToModdedBiomes = true
netherSoulTempleSpawnrate = 26
addNetherSoulTempleToModdedBiomes = true
[RSTemplesConfig.pyramids]
netherPyramidSpawnrate = 32
addNetherPyramidToModdedBiomes = true
badlandsPyramidSpawnrate = 20
addBadlandsPyramidToModdedBiomes = true
[RSMineshaftsConfig]
lootChestsMS = true
addMineshaftsToModdedBiomes = true

[RSMineshaftsConfig.spawnrate]
birchMineshaftSpawnrate = 40
jungleMineshaftSpawnrate = 40
desertMineshaftSpawnrate = 40
stoneMineshaftSpawnrate = 40
savannaMineshaftSpawnrate = 40
icyMineshaftSpawnrate = 40
oceanMineshaftSpawnrate = 40
taigaMineshaftSpawnrate = 40
swampAndDarkForestMineshaftSpawnrate = 40
endMineshaftSpawnrate = 40
netherMineshaftSpawnrate = 40

[RSMineshaftsConfig.minHeight]
birchMineshaftMinHeight = 5
jungleMineshaftMinHeight = 5
desertMineshaftMinHeight = 5
stoneMineshaftMinHeight = 5
savannaMineshaftMinHeight = 5
icyMineshaftMinHeight = 5
oceanMineshaftMinHeight = 5
taigaMineshaftMinHeight = 5
swampAndDarkForestMineshaftMinHeight = 5
endMineshaftMinHeight = 30
netherMineshaftMinHeight = 5

[RSMineshaftsConfig.maxHeight]
birchMineshaftMaxHeight = 45
jungleMineshaftMaxHeight = 45
desertMineshaftMaxHeight = 45
stoneMineshaftMaxHeight = 45
savannaMineshaftMaxHeight = 45
icyMineshaftMaxHeight = 45
oceanMineshaftMaxHeight = 25
taigaMineshaftMaxHeight = 45
swampAndDarkForestMineshaftMaxHeight = 45
endMineshaftMaxHeight = 37
netherMineshaftMaxHeight = 13

[RSMineshaftsConfig.misc]
barrensIslandsEndMineshafts = false
[RSStrongholdsConfig]
strongholdSizeSH = 100.0
allowExtraSpawnersSH = true
lootChestsSH = true

[RSStrongholdsConfig.stonebrick]
allowStonebrickStronghold = true
addStonebrickStrongholdToModdedBiomes = true
silverfishSpawnrateSH = 0.8
stonebrickStrongholdMinHeight = 0
stonebrickStrongholdMaxHeight = 45
stonebrickStrongholdSpawnrate = 85
stonebrickStrongholdChainSpawnrate = 35

[RSStrongholdsConfig.nether]
netherStrongholdSpawnrate = 85
addNetherStrongholdToModdedBiomes = true
netherStrongholdMinHeight = 33
netherStrongholdMaxHeight = 36
netherStrongholdChainSpawnrate = 50
[RSOutpostsConfig.outposts]
netherBrickOutpostSpawnrate = 21
addNetherBrickOutpostToModdedBiomes = true
warpedOutpostSpawnrate = 21
addWarpedOutpostToModdedBiomes = false
crimsonOutpostSpawnrate = 21
addCrimsonOutpostToModdedBiomes = false
[RSVillagesConfig]
addVillagesToModdedBiomes = true
badlandsVillageSpawnrate = 17
birchVillageSpawnrate = 28
darkForestVillageSpawnrate = 28
jungleVillageSpawnrate = 26
swampVillageSpawnrate = 28
mountainsVillageSpawnrate = 28
giantTaigaVillageSpawnrate = 26
[RSWellsConfig]
addWellsToModdedBiomes = true
canHaveBells = true

[RSWellsConfig.spawnrate]
badlandsWellSpawnrate = 350
netherWellSpawnrate = 350
snowWellSpawnrate = 350
mossyStoneWellSpawnrate = 350
forestWellSpawnrate = 350
